version: '3'

services:
  base:
    build:
      context: .
    volumes:
      - '.:/app'

  terminal:
    build:
      context: .
    volumes:
      - '.:/app'
    command: sh

  test:
    build:
      context: .
    command: rake test
